### PR TITLE
Remake read_template() as Template class.

### PR DESCRIPTION
**Pull request by peria**
no instances are made, though.

### CODE REVIEW

**Comment by mayah** [comment]
How do we use this?

**Comment by mayah** [comment]
I mean, how do we add template score?

**Comment by peria** [comment]
It seems that some member variables of COMAI_HI were removed in past CLs, and we can use member variables of an `Template` instance instead of them.

**Comment by peria** [comment]
and I think the instance of `Template` will be a member variable of `COMAI_HI`.

**Comment by mayah** [comment]
There are the commit that I removed read_template().

[1] https://github.com/puyoai/puyoai/pull/108/commits
[2] https://github.com/puyoai/puyoai/commit/df9549b7af81439c1d11b1aaac6a870eab3a495d

read_template() is removed from (1), and (2) removes a few more members.
This shows we don't have any method to evaluate template matching.

It's OK for me to revive read_template(), but we don't have any code to evaluate template yet? Do you have a plan to write by yourself?

**Comment by peria** [comment]
Hmm, the original code seems not to have code to match templates, and I'm not willing to make it.
(I think it was around the code which was removed with 8304388007b8c715bb3ccca2a2a33b4e70d797f4)

**Comment by peria** [comment]
Let me abandon this CL.  It seems useless, as you commented.

**Pull request closed without merging**
