### PR TITLE
Don't use static_cast to convert int to TLColor.

### PR DESCRIPTION
**Pull request by mayah**
Define NORMAL_TLCOLORS to convert int to TLColor, and use it.

### CODE REVIEW

**Comment by peria** [comment]
Could you add the objective of this CL?
Yes, the description explains what it does, but I cannot get why it does.

**Comment by peria** [comment]
IIRC, the argument of `isTLNormalColor()` uses `TLColor(ba[][])` in most cases.
It maybe good to work also for them.

**Comment by mayah** [comment]
addressed.

**Comment by peria** [comment]
LGTM. Thanks.

**Pull request merged**
