### PR TITLE
[niina] Refactoring of 2-double part

### PR DESCRIPTION
**Pull request by peria**
BUG=#127

### CODE REVIEW

**Comment by peria** [comment]
need to be committed after #158

**Comment by mayah** [comment]
Could you rebase this on ToT?

**Comment by peria** [comment]
rebase is done.
but please wait until my next announcement.
I have to split this CL into 2 CLs.

**Comment by peria** [comment]
Rebased on #160.
Please review it before this.

**Comment by mayah** [comment]
LGTM.

**Pull request merged**
