### PR TITLE
Use TLColor for all color variables.

### PR DESCRIPTION
**Pull request by mayah**
Just replaced int to TLColor for all color variables.
Patch is too big. I'll split this to several pieces...

### CODE REVIEW

**Comment by mayah** [comment]
It's time to use TLColor for variables.

**Comment by mayah** [comment]
After merging this, we might be able to use our PuyoColor ?

**Comment by peria** [comment]
LGTM, and merging.
We can work for a nit comment in another CL.

**Comment by peria** [comment]
Before replacing `TLColor` with our `PuyoColor`, we need to change `enum` values inside of `TLColor`.  It will also need to change some code.

**Pull request merged**
