### PR TITLE
Avoid accessing out of range in some cases

### PR DESCRIPTION
**Pull request by peria**
To reduce possibility of accessing out of range, I add some checks.

### CODE REVIEW

**Comment by peria** [comment]
mayah@, PTL.

**Comment by mayah** [comment]
It's better to the split the patch for PR. Though the first commit is good, I cannot merge it...

**Comment by peria** [comment]
> It's better to the split the patch for PR.
Right.  I'll do so in future PRs.

**Comment by mayah** [comment]
ok if it is commented that RED has no meaning.

**Comment by mayah** [comment]
LGTM

**Comment by peria** [comment]
Thanks for your comments.

**Pull request merged**
