### PR TITLE
Add a simple random library

### PR DESCRIPTION
**Pull request by peria**
You can use standard `rand()` but it is known as bad and slow one.
This library supplies a fast and good pseudo random generator.
It also proves static functions, so you can use them instead of bad `rand()`.

### CODE REVIEW

**Comment by mayah** [comment]
Why don't you use mt19937 and uniform_int_distribution?
It's included in C++11 library. You can use them with `#include <random>`

**Comment by mayah** [comment]
c.f. http://en.cppreference.com/w/cpp/numeric/random

**Comment by mayah** [comment]
And we're using it already.
e.g. src/core/sequence_generator.cc

**Comment by peria** [comment]
Thank you for the information.
I'll use it.

**Pull request closed without merging**
